# Generated by Django 4.2 on 2024-08-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_nutrient'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='nutrients',
            field=models.ManyToManyField(to='core.nutrient'),
        ),
    ]
