# Generated by Django 4.2.15 on 2024-09-04 21:00

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_nutrient_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutrient',
            name='image',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.ingredient_image_file_path),
        ),
    ]
